version: '3.8'

services:
  db:
    image: postgres:15
    container_name: estoque_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2Rd11=$"
      POSTGRES_DB: sistema_estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: