version: '3.8'

services:
  # --- SERVIÇO DO BANCO DE DADOS ---
  db:
    image: postgres:15
    container_name: estoque_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- NOVO: SERVIÇO DO SERVIDOR (BACKEND) ---
  app:
    build: ./backend          # Diz ao Docker para procurar o seu 'Dockerfile' na pasta atual
    container_name: estoque_api
    restart: always
    ports:
      - "3000:3000"   # Túnel: Porta 3000 do Windows -> Porta 3000 do Docker
    environment:
      DB_USER: ${DB_USER}
      DB_PASS:  ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db     # Importante: No Docker, o host é o nome do serviço (db), não localhost
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db            # Avisa ao Docker para ligar o banco ANTES de ligar o servidor
    volumes:
      - ./backend:/usr/src/app # "Espelhamento": O que mudar no VS Code muda no Docker na hora!
      - /usr/src/app/node_modules # Evita que o Docker sobrescreva as dependências

# DECLARAÇÃO GLOBAL: Aqui apenas listamos os nomes dos volumes (sem traços ou caminhos)
volumes:
  postgres_data:


